<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Analytics Report - <?php echo e($period); ?> Days</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 0;
            padding: 20px;
            line-height: 1.4;
            color: #333;
        }

        .header {
            text-align: center;
            border-bottom: 2px solid #2563eb;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }

        .clinic-name {
            font-size: 24px;
            font-weight: bold;
            color: #2563eb;
            margin-bottom: 10px;
        }

        .report-title {
            font-size: 18px;
            font-weight: bold;
            margin-bottom: 10px;
        }

        .report-meta {
            font-size: 11px;
            color: #666;
            margin-bottom: 20px;
        }

        .summary-section {
            display: table;
            width: 100%;
            margin-bottom: 30px;
            border: 1px solid #ddd;
            border-radius: 5px;
            overflow: hidden;
        }

        .summary-row {
            display: table-row;
        }

        .summary-cell {
            display: table-cell;
            padding: 15px;
            border-bottom: 1px solid #ddd;
            text-align: center;
        }

        .summary-cell:first-child {
            background-color: #f8f9fa;
            font-weight: bold;
            width: 200px;
            text-align: left;
        }

        .summary-cell.large {
            font-size: 16px;
            font-weight: bold;
            color: #2563eb;
        }

        .section-title {
            font-size: 16px;
            font-weight: bold;
            color: #2563eb;
            margin: 30px 0 15px 0;
            padding-bottom: 5px;
            border-bottom: 1px solid #e5e7eb;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
        }

        table, th, td {
            border: 1px solid #ddd;
        }

        th, td {
            padding: 8px 12px;
            text-align: left;
        }

        th {
            background-color: #f8f9fa;
            font-weight: bold;
            font-size: 11px;
        }

        tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        .chart-placeholder {
            border: 1px dashed #ccc;
            padding: 40px;
            text-align: center;
            margin: 20px 0;
            color: #666;
            font-style: italic;
        }

        .footer {
            margin-top: 50px;
            padding-top: 20px;
            border-top: 1px solid #e5e7eb;
            font-size: 10px;
            color: #666;
            text-align: center;
        }

        .total-row {
            background-color: #e3f2fd !important;
            font-weight: bold;
        }

        .currency::before {
            content: "₱";
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="clinic-name">EVERBRIGHT POLYCLINIC</div>
        <div class="report-title">Analytics Report</div>
        <div class="report-meta">
            Report Period: <?php echo e($start_date); ?> to <?php echo e($end_date); ?> (<?php echo e($period); ?> days)<br>
            Generated on: <?php echo e($generated_at); ?><br>
            Generated by: <?php echo e($generated_by); ?>

        </div>
    </div>

    <div class="summary-section">
        <div class="summary-row">
            <div class="summary-cell">Total Appointments</div>
            <div class="summary-cell large"><?php echo e(number_format($total_appointments)); ?></div>
        </div>
        <div class="summary-row">
            <div class="summary-cell">Completed Appointments</div>
            <div class="summary-cell"><?php echo e(number_format($completed_appointments)); ?></div>
        </div>
        <div class="summary-row">
            <div class="summary-cell total-row">Total Revenue</div>
            <div class="summary-cell large total-row currency"><?php echo e($total_revenue); ?></div>
        </div>
    </div>

    <div class="section-title">Branch Performance Comparison</div>
    <table>
        <thead>
            <tr>
                <th>Branch Name</th>
                <th>Appointments</th>
                <th>Revenue</th>
            </tr>
        </thead>
        <tbody>
            <?php $__currentLoopData = $branch_performance; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $branch): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
            <tr>
                <td><?php echo e($branch['name']); ?></td>
                <td><?php echo e(number_format($branch['appointments'])); ?></td>
                <td class="currency"><?php echo e($branch['revenue']); ?></td>
            </tr>
            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
        </tbody>
    </table>

    <div class="section-title">Weekly Trends</div>
    <table>
        <thead>
            <tr>
                <th>Period</th>
                <th>Appointments</th>
                <th>Revenue</th>
            </tr>
        </thead>
        <tbody>
            <?php $__currentLoopData = $weekly_data; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $week): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
            <tr>
                <td><?php echo e($week['week']); ?></td>
                <td><?php echo e(number_format($week['appointments'])); ?></td>
                <td class="currency"><?php echo e(number_format($week['revenue'], 2)); ?></td>
            </tr>
            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
        </tbody>
    </table>

    <div class="chart-placeholder">
        [Chart would be displayed here showing revenue and appointment trends over time]
    </div>

    <div class="chart-placeholder">
        [Bar chart showing appointment types distribution]
    </div>

    <div class="section-title">Key Performance Metrics</div>
    <div class="summary-section">
        <div class="summary-row">
            <div class="summary-cell">Completion Rate</div>
            <div class="summary-cell">
                <?php if($total_appointments > 0): ?>
                    <?php echo e(number_format(($completed_appointments / $total_appointments) * 100, 1)); ?>%
                <?php else: ?>
                    N/A
                <?php endif; ?>
            </div>
        </div>
        <div class="summary-row">
            <div class="summary-cell">Average Revenue per Appointment</div>
            <div class="summary-cell">
                <?php if($total_appointments > 0): ?>
                    <span class="currency"><?php echo e(number_format($total_revenue / $total_appointments, 2)); ?></span>
                <?php else: ?>
                    N/A
                <?php endif; ?>
            </div>
        </div>
        <div class="summary-row">
            <div class="summary-cell">Active Branches</div>
            <div class="summary-cell"><?php echo e(count($branch_performance)); ?></div>
        </div>
    </div>

    <div class="footer">
        <p>This report contains confidential business information. Please handle accordingly.</p>
        <p>Report generated by EverBright Polyclinic Analytics System</p>
    </div>
</body>
</html>
<?php /**PATH C:\Users\admin\Everbright-Optical-Clinic ni Johnro\backend\resources\views/pdf/analytics-report.blade.php ENDPATH**/ ?>