<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Analytics Report - {{ $generatedAt->format('F Y') }}</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 20px;
            color: #333;
            line-height: 1.6;
        }
        
        .header {
            text-align: center;
            border-bottom: 3px solid #2563eb;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        
        .header h1 {
            color: #2563eb;
            margin: 0;
            font-size: 28px;
        }
        
        .header .subtitle {
            color: #666;
            margin: 5px 0;
            font-size: 16px;
        }
        
        .report-info {
            background: #f8fafc;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 25px;
            border-left: 4px solid #2563eb;
        }
        
        .report-info h3 {
            margin: 0 0 10px 0;
            color: #2563eb;
        }
        
        .report-info p {
            margin: 5px 0;
            font-size: 14px;
        }
        
        .section {
            margin-bottom: 30px;
            page-break-inside: avoid;
        }
        
        .section h2 {
            color: #1e40af;
            border-bottom: 2px solid #e5e7eb;
            padding-bottom: 8px;
            margin-bottom: 15px;
            font-size: 20px;
        }
        
        .metrics-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 15px;
            margin-bottom: 20px;
        }
        
        .metric-card {
            background: #ffffff;
            border: 1px solid #e5e7eb;
            border-radius: 8px;
            padding: 15px;
            text-align: center;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
        }
        
        .metric-value {
            font-size: 24px;
            font-weight: bold;
            color: #2563eb;
            margin-bottom: 5px;
        }
        
        .metric-label {
            font-size: 14px;
            color: #666;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        
        .table th,
        .table td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #e5e7eb;
        }
        
        .table th {
            background: #f8fafc;
            font-weight: bold;
            color: #374151;
        }
        
        .table tr:nth-child(even) {
            background: #f9fafb;
        }
        
        .rating {
            display: inline-block;
            color: #f59e0b;
            font-weight: bold;
        }
        
        .positive {
            color: #059669;
        }
        
        .negative {
            color: #dc2626;
        }
        
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e5e7eb;
            text-align: center;
            color: #666;
            font-size: 12px;
        }
        
        .page-break {
            page-break-before: always;
        }
        
        .highlight {
            background: #fef3c7;
            padding: 2px 6px;
            border-radius: 4px;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>📊 Analytics Report</h1>
        <div class="subtitle">Optical Clinic Management System</div>
        <div class="subtitle">{{ $generatedAt->format('F d, Y \a\t g:i A') }}</div>
    </div>

    <div class="report-info">
        <h3>📋 Report Summary</h3>
        <p><strong>Period:</strong> {{ $startDate->format('M d, Y') }} - {{ $endDate->format('M d, Y') }} ({{ $period }} days)</p>
        <p><strong>Generated By:</strong> {{ $generatedBy }}</p>
        <p><strong>Generated At:</strong> {{ $generatedAt->format('M d, Y \a\t g:i A') }}</p>
        @if($branchId)
            <p><strong>Branch Filter:</strong> {{ \App\Models\Branch::find($branchId)->name ?? 'Unknown Branch' }}</p>
        @else
            <p><strong>Scope:</strong> All Branches</p>
        @endif
    </div>

    <!-- Revenue Section -->
    <div class="section">
        <h2>💰 Revenue Analytics</h2>
        <div class="metrics-grid">
            <div class="metric-card">
                <div class="metric-value">₱{{ number_format($analytics['revenue']['total'], 2) }}</div>
                <div class="metric-label">Total Revenue</div>
            </div>
            <div class="metric-card">
                <div class="metric-value">₱{{ number_format($analytics['revenue']['reservations'], 2) }}</div>
                <div class="metric-label">Reservations</div>
            </div>
            <div class="metric-card">
                <div class="metric-value">₱{{ number_format($analytics['revenue']['receipts'], 2) }}</div>
                <div class="metric-label">Receipts</div>
            </div>
        </div>
    </div>

    <!-- Appointments Section -->
    <div class="section">
        <h2>📅 Appointment Analytics</h2>
        <div class="metrics-grid">
            <div class="metric-card">
                <div class="metric-value">{{ $analytics['appointments']['total'] }}</div>
                <div class="metric-label">Total Appointments</div>
            </div>
            <div class="metric-card">
                <div class="metric-value positive">{{ $analytics['appointments']['completed'] }}</div>
                <div class="metric-label">Completed</div>
            </div>
            <div class="metric-card">
                <div class="metric-value negative">{{ $analytics['appointments']['cancelled'] }}</div>
                <div class="metric-label">Cancelled</div>
            </div>
            <div class="metric-card">
                <div class="metric-value highlight">{{ $analytics['appointments']['completion_rate'] }}%</div>
                <div class="metric-label">Completion Rate</div>
            </div>
        </div>
    </div>

    <!-- Feedback Section -->
    <div class="section">
        <h2>⭐ Customer Feedback Analytics</h2>
        <div class="metrics-grid">
            <div class="metric-card">
                <div class="metric-value">{{ $analytics['feedback']['total'] }}</div>
                <div class="metric-label">Total Feedback</div>
            </div>
            <div class="metric-card">
                <div class="metric-value rating">{{ $analytics['feedback']['avg_rating'] }}/5</div>
                <div class="metric-label">Average Rating</div>
            </div>
            <div class="metric-card">
                <div class="metric-value">{{ $analytics['feedback']['unique_customers'] }}</div>
                <div class="metric-label">Unique Customers</div>
            </div>
            <div class="metric-card">
                <div class="metric-value highlight">{{ $analytics['feedback']['response_rate'] }}%</div>
                <div class="metric-label">Response Rate</div>
            </div>
        </div>
    </div>

    <!-- Branch Performance -->
    @if(count($analytics['branch_performance']) > 0)
    <div class="section">
        <h2>🏢 Branch Performance</h2>
        <table class="table">
            <thead>
                <tr>
                    <th>Branch Name</th>
                    <th>Appointments</th>
                    <th>Revenue</th>
                    <th>Avg Rating</th>
                </tr>
            </thead>
            <tbody>
                @foreach($analytics['branch_performance'] as $branch)
                <tr>
                    <td><strong>{{ $branch['name'] }}</strong></td>
                    <td>{{ $branch['appointments'] }}</td>
                    <td>₱{{ number_format($branch['revenue'], 2) }}</td>
                    <td>
                        <span class="rating">{{ $branch['avg_rating'] }}/5</span>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @endif

    <!-- Top Services -->
    @if(count($analytics['top_services']) > 0)
    <div class="section">
        <h2>🔝 Top Services</h2>
        <table class="table">
            <thead>
                <tr>
                    <th>Service Type</th>
                    <th>Appointments</th>
                    <th>Percentage</th>
                </tr>
            </thead>
            <tbody>
                @foreach($analytics['top_services'] as $service)
                <tr>
                    <td><strong>{{ ucfirst($service->type) }}</strong></td>
                    <td>{{ $service->count }}</td>
                    <td>{{ $analytics['appointments']['total'] > 0 ? round(($service->count / $analytics['appointments']['total']) * 100, 1) : 0 }}%</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @endif

    <!-- Recent Feedback -->
    @if(count($analytics['recent_feedback']) > 0)
    <div class="section page-break">
        <h2>💬 Recent Customer Feedback</h2>
        <table class="table">
            <thead>
                <tr>
                    <th>Customer</th>
                    <th>Branch</th>
                    <th>Rating</th>
                    <th>Comment</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach($analytics['recent_feedback'] as $feedback)
                <tr>
                    <td><strong>{{ $feedback->customer->name ?? 'Unknown' }}</strong></td>
                    <td>{{ $feedback->branch->name ?? 'Unknown' }}</td>
                    <td>
                        <span class="rating">{{ $feedback->rating }}/5</span>
                    </td>
                    <td>{{ $feedback->comment ? Str::limit($feedback->comment, 50) : 'No comment' }}</td>
                    <td>{{ $feedback->created_at->format('M d, Y') }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @endif

    <div class="footer">
        <p>This report was generated automatically by the Optical Clinic Management System</p>
        <p>For questions or concerns, please contact the system administrator</p>
    </div>
</body>
</html>

